### ISSUE TITLE
Release ACE 5.3

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/ace#19]
A number of changes accumulated since ACE 5.2 on 11/03/2016 almost 4 years ago. Time for a nw release?

**Comment by alex-konovalov** [comment]
Pinging @gregg0 and @fingolfin as maintainers.

**Comment by fingolfin** [comment]
Yes, a release is long overdue. It would also fix #10. @gregg0 I can take care of it, and will do so by the end of the week, unless I hear an objection from you (and earlier if you approve)

**Comment by gregg0** [comment]
Dear Max

Sorry for not being so communicative.
So broken links to the main manuals ... what's the intention?
... leave them broken?
... or do by-hand fixes that will probably break again as soon as there are any changes
     made to the main manuals
     ... it's probably do-able, since there are only a handful of them.
I tried to find explanation of #10
... but maybe it's just my inexperience at reading what's there.

I was just made redundant, at Curtin, as of December 13 which was a Friday(?!),
so I've probably got more time to do things now.
The amusing thing is I've been expecting the axe to fall every year for the last 17 years,
which is why I had things at UWA, not Curtin.
Anyway, I'm finally free of the place.

Regards,
Greg



________________________________

**Comment by fingolfin** [comment]
Greg, the broken links are already taken care of. To quote what I wrote in #10: 
> This was a problem with the release wrapping, and will be automatically fixed in the next release.

**Comment by gregg0** [comment]
Dear Max

I read that ... but I didn't have any confidence that those links would be fixed
automatically. It's been too long since I've done a release wrapping, I guess.
Anyway, I approve.
Is there any value in working on moving the documentation to GAPDoc?

Regards,
Greg

________________________________

**Comment by fingolfin** [comment]
@gregg0 sure that would be useful -- but not for this release! I'd rather release what we have *now*, and not wait for other changes that might or might not come; if those changes come, we can simply make another release. There's no harm in that, after all :-)

**Comment by gregg0** [comment]
No worries Max

I'm sure, it will take me a while to get going with it.
Go for it.

Regards
Greg
________________________________

**Comment by fingolfin** [comment]
I just released ACE 5.3
